### ISSUE TITLE
Introduce "SG" in the PDF Descriptions

### ISSUE THREAD

**Issue by schmidni** [swiss-seismological-service/REIA-web#19]
### User Story
As a user of the products of RIA I need to know what "SG" means, therefore this should be described in the description on the second page of the PDF's.

### Acceptance Criteria
The sentence «Es werden fünf verschiedene Schadensgrade (SG) an Gebäuden unterschieden» should include the (SG) in all languages so that it is clear what this means.
**(SG)** should be used in all languages and not be "translated".

**Comment by romanoe** [comment]
I confused SG for italian and french. New pull request to fix this.
