### ISSUE TITLE
Change the "Additional Data" link to point to correct language

### ISSUE THREAD

**Issue by schmidni** [swiss-seismological-service/REIA-web#45]
### User Story
As a consumer of the RIA sheet, I would like the "Additional Data" Link to point to the Event page in the same language as the sheet I'm looking at is in.

### Acceptance Criteria
The "LINK", shown in the screenshot below, should point to the same language of the webpage as the current sheet.

![Image](https://github.com/swiss-seismological-service/REIA-web/assets/40888729/12f789c7-6f72-4ec9-b21a-6131bcd76f15)

### Bonus
The base link is set in the env file and you can ask Cyrill for the link of the d-line OCMS installation so it also works on d-line.

**Comment by romanoe** [comment]
Does the word "Link" need to be translated as well ?

**Comment by schmidni** [comment]
Huh, thats a good question. I think in german it would also be "Link" anyways, french it would probably make sense to use lien afaik, and in italian you're the expert ;)

If you want to be sure, ask somebody from communications, but I think you could decide on your own if it makes more sense in italian and french to translate.
