### ISSUE TITLE
Print PDF's as using pdf/a standard

### ISSUE THREAD

**Issue by schmidni** [swiss-seismological-service/REIA-web#53]
Very accurate problem description from Philipp:

> 
> (vgl. Screenshots unten: Farbverläufe statt Diagramme)
> Ich mache die .png-Previews der RIA-Sheets für die NAZ, indem ich die PDFs vom PDF-Printer herunterlade und mit PyMuPDF (getestet 1.16.11 und 1.25.5, das ist das jüngste Release) nach png konvertiere. PyMuPDF wrappt MuPDF, eine ziemlich weit verbreitete C-Library für PDF-Management. Offenbar hat die PDF-Geschmacksrichtung von Chrome ein Feature, das PyMuPDF nicht passt. In der Folge kann z.B. schon mein Standard-Linux-PDFviewer die Sheets nicht korrekt darstellen. (es gibt also evtl. noch mehr Nutzer, die damit Probleme haben).
> Ich habe mal versucht, das PDF mit Acrobat nach PDF/A zu konvertieren. Danach stellen es MuPDF-basierte Viewer richtig dar, und auch meine Konversion funktioniert. Und da offene Standards wie PDF/A eh eine gute Sache sind, wollte ich fragen:
> 
> Hat der PDF-Printer eine Option, um ihn standardmässig auf PDF/A zu trimmen?
> 

### Acceptance Criteria
Pdfs generated using the `web-pdf-generator` application are already converted to the PDF/A standard and are correctly displayed using eg. the MuPDF viewer.

![Image](https://github.com/swiss-seismological-service/REIA-web/assets/40888729/f4ab6df3-09a2-42e9-99b0-6283f67daa47)
![Image](https://github.com/swiss-seismological-service/REIA-web/assets/40888729/383a8927-6b7b-4cdd-96f6-bdeed2b32b99)

**Comment by kaestli** [comment]
(note - not only acrobat, but also ghostscript understands the initial pdf format sufficiently to convert it in a pdf/a which displays correctly using MuPDF based viewers. So we are probably working around a MuPDF bug here. Anyway...)

**Comment by romanoe** [comment]
@kaestli Does your PDF/A export with Acrobat maintain the same original quality and size of the file ? 

I attempted to use ghostscript  to convert it to PDF/A, but unfortunately, this process rasterizes the first page, making the text no longer searchable and selectable (see [ria_report_ghostscript.pdf](https://github.com/user-attachments/files/16053827/ria_report_ghostscript.pdf)). Any clue ?

**Comment by romanoe** [comment]
After investigation: 

- The problem has been resolved on the NAZ web page by rasterizing the entire page (PDF to PDF/A with ghostscript), which works for this use case, but not for consultation purposes

-  There is no easy solution to achieve consistent PDFs across all viewers. Similar issues have already been raised for these specific PDF viewers (Evince, MUPDF), but as mentioned, the workarounds are not straightforward.

- Online consultation (HTML) is the recommended approach and the safest in terms of compatibility. If PDF consultation is needed, Adobe Acrobat, recent Mac document viewer, and browser viewers are the way to go. We should eventually advise users not to use Evince and MuPDF
