### ISSUE TITLE
Change Tick Values on Scales

### ISSUE THREAD

**Issue by schmidni** [swiss-seismological-service/REIA-web#54]
### User Story
As somebody who is looking at the RIA Sheets, it is currently difficult to read a value from the first part of the scales on the RIA sheets.

### Acceptance Criteria
Instead of "Keine", currently corresponding to 0, the lowest value should be written out as below and correspond to the respective value.
The code modules for the SED Website also need to be updated as a result.

### Hints
The scale is currently implemented in a rather complex way, because my assumption up until now was, that "keine" corresponds to 0. Therefore the first tick can be a scale from 0.01 (log(0) does not exist) to 10 Million (spanning logarithmic scales from 0.01, 0.1, 1, 10, 100, ...), whereas the second tick has the same width on the sheet, but only goes from 10 Mio to 100 Mio.

You probably don't need to change this, but just as an explanation if you find the implementations strange.

![Image](https://github.com/swiss-seismological-service/REIA-web/assets/40888729/57d08555-a02d-41bf-b672-53e06a99f9f3)

**Comment by romanoe** [comment]
With the current configuration, the tick container for building damage is not big enough to display the value (<= 1Mo CHF) on one line. This increases the space between the labels and the ticks for the rest of the labels.

![Screenshot from 2024-07-04 14-25-47](https://github.com/swiss-seismological-service/REIA-web/assets/32194904/8af0a0ef-6186-481c-a117-22a7421d90fd)

Possible solutions to address this issue:

- Increase the width of the first label to 15% and decrease the width of the second label to 15% (from the default 20%), in order to align with the fixed color stops:
 https://github.com/swiss-seismological-service/REIA-web/blob/328cb587d4ce7eae2b2807e368cb46c21742575e/src/js/utils/ColorScale.js#L17-L22 )
- Increase the width of the first label and adjust the color stops percentages accordingly, though I am uncertain if this will yield the correct result.
- Decrease font size of the labels

If not an issue, then I proceed for the pull request.

**Comment by schmidni** [comment]
Are there any drawbacks on the first option? if not then just go ahead. :)

**Comment by schmidni** [comment]
@romanoe

Sorry for the whole mess. I didn't check the pull request properly and had to revert the whole thing. Please make sure to update your local repository on all branches, as I had to do a couple for force pushes to undo the merge.

`Instead of "Keine", currently corresponding to 0, the lowest value should be written out as below and correspond to the respective value.`

I was not very clear enough, but not only the label needs to be updated, but also the underlying value on the scale -> The label was keine=0 (or almost 0), and now the label needs to be a value>0 and the value on the scale needs to be that same value...

**Comment by schmidni** [comment]
> With the current configuration, the tick container for building damage is not big enough to display the value (<= 1Mo CHF) on one line. This increases the space between the labels and the ticks for the rest of the labels.
> 
> ![Screenshot from 2024-07-04 14-25-47](https://private-user-images.githubusercontent.com/32194904/345830075-8af0a0ef-6186-481c-a117-22a7421d90fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjgzNjAsIm5iZiI6MTcyMDQyODA2MCwicGF0aCI6Ii8zMjE5NDkwNC8zNDU4MzAwNzUtOGFmMGEwZWYtNjE4Ni00ODFjLWExMTctMjJhNzQyMWQ5MGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4NDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MmZjYjFhZjg3NzU5NDM0Nzk0OTg5ODcwNjc2MDJhYjZhNGYwMTY0ZDc3MjliZWRmNDJiZjI5OGIyNzM5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_wZRR5Dg_JGrNBkD_dhlVIvcFLrmys4OHfr0v0mIuw)
> 
> Possible solutions to address this issue:
> 
> * Increase the width of the first label to 15% and decrease the width of the second label to 15% (from the default 20%), in order to align with the fixed color stops:
>   https://github.com/swiss-seismological-service/REIA-web/blob/328cb587d4ce7eae2b2807e368cb46c21742575e/src/js/utils/ColorScale.js#L17-L22
>    )
> * Increase the width of the first label and adjust the color stops percentages accordingly, though I am uncertain if this will yield the correct result.
> * Decrease font size of the labels
> 
> If not an issue, then I proceed for the pull request.

While you're at it, I looked at how it looks now, I think it is okay, but would it also be an option to have the first tick on 2 lines without increasing (or only a little) the distance between the colorbar and the tickvalues? Just a thought, you can also just run it by Michele, she's got the last word on those things.
